/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.klijent.Klijent;
import java.awt.List;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import kontroler.KontrolerKlijent;

/**
 *
 * @author Korisnik
 */
public class KlijentGUIp extends javax.swing.JFrame {

    Klijent k;
    
    public KlijentGUIp(Klijent k) {
        this.k = k;
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int x = JOptionPane.showConfirmDialog(null, 
                        "Da li zelite da izadjete iz chat-a?",
                            "Izlaz", JOptionPane.YES_NO_OPTION,
                                JOptionPane.INFORMATION_MESSAGE);
                if (x == JOptionPane.YES_OPTION) {
                    System.exit(0);
                    KontrolerKlijent.zatvaranje();
                }
            }
            
        });
        this.getTxtNovaPoruka().requestFocus();
        getTxtAktivanKorisnik().setText(KontrolerKlijent.getAktivniKlijent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGlavni = new javax.swing.JPanel();
        lblPoruka = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPoruka = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtNovaPoruka = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPosalji = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAktivanKorisnik = new javax.swing.JTextField();
        listAktivniKlijenti = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chat Klijent");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(435, 270));
        setPreferredSize(new java.awt.Dimension(650, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblPoruka.setText("Chat:");

        txtPoruka.setEditable(false);
        txtPoruka.setColumns(20);
        txtPoruka.setRows(5);
        jScrollPane1.setViewportView(txtPoruka);

        jLabel1.setText("Nova poruka:");

        txtNovaPoruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaPorukaActionPerformed(evt);
            }
        });
        txtNovaPoruka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNovaPorukaKeyPressed(evt);
            }
        });

        jLabel2.setText("Aktivni klijenti:");

        btnPosalji.setText("Posalji");
        btnPosalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiActionPerformed(evt);
            }
        });

        jLabel3.setText("Klijent: ");

        txtAktivanKorisnik.setEditable(false);

        listAktivniKlijenti.setMultipleMode(true);

        javax.swing.GroupLayout pnlGlavniLayout = new javax.swing.GroupLayout(pnlGlavni);
        pnlGlavni.setLayout(pnlGlavniLayout);
        pnlGlavniLayout.setHorizontalGroup(
            pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlavniLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGlavniLayout.createSequentialGroup()
                        .addComponent(txtNovaPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGlavniLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAktivanKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listAktivniKlijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlGlavniLayout.setVerticalGroup(
            pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlavniLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAktivanKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlGlavniLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(pnlGlavniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNovaPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPosalji, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(listAktivniKlijenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getContentPane().add(pnlGlavni, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("ChatServer");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPosaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiActionPerformed
        KontrolerKlijent.posalji();    
    }//GEN-LAST:event_btnPosaljiActionPerformed

    private void txtNovaPorukaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNovaPorukaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            KontrolerKlijent.posalji();
            getTxtNovaPoruka().setText("");
        }
    }//GEN-LAST:event_txtNovaPorukaKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void txtNovaPorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaPorukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaPorukaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosalji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPoruka;
    private java.awt.List listAktivniKlijenti;
    private javax.swing.JPanel pnlGlavni;
    private javax.swing.JTextField txtAktivanKorisnik;
    private javax.swing.JTextField txtNovaPoruka;
    private javax.swing.JTextArea txtPoruka;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnPosalji() {
        return btnPosalji;
    }

    public void setBtnPosalji(JButton btnPosalji) {
        this.btnPosalji = btnPosalji;
    }

    public JPanel getPnlGlavni() {
        return pnlGlavni;
    }

    public void setPnlGlavni(JPanel pnlGlavni) {
        this.pnlGlavni = pnlGlavni;
    }

    public final JTextField getTxtNovaPoruka() {
        return txtNovaPoruka;
    }

    public void setTxtNovaPoruka(JTextField txtNovaPoruka) {
        this.txtNovaPoruka = txtNovaPoruka;
    }

    public JTextArea getTxtPoruka() {
        return txtPoruka;
    }

    public void setTxtPoruka(JTextArea txtPoruka) {
        this.txtPoruka = txtPoruka;
    }

    public JTextField getTxtAktivanKorisnik() {
        return txtAktivanKorisnik;
    }

    public void setTxtAktivanKorisnik(JTextField txtAktivanKorisnik) {
        this.txtAktivanKorisnik = txtAktivanKorisnik;
    }

    public List getListAktivniKlijenti() {
        return listAktivniKlijenti;
    }

    public void setListAktivniKlijenti(List listAktivniKlijenti) {
        this.listAktivniKlijenti = listAktivniKlijenti;
    }

}
